apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: openhack6-ingress-api
  namespace: api-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
#works not with host ... --> failed witth roue to default-backend  - host: openhack6.northeurope.cloudapp.azure.com
  - http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi
        #path: /api/poi(/|$)(.*)
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: openhack6-ingress-web
  namespace: web-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
#  - host: openhack6.northeurope.cloudapp.azure.com
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /
