apiVersion: v1
kind: Namespace
metadata:
  name: insurance
---
apiVersion: v1
kind: LimitRange
metadata:
    name: mem-limit-range
    namespace: insurance
spec:
    limits:
    - default:
        memory: 2Gi
    defaultRequest:
        memory: 256Mi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  namespace: insurance
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
        - image: "registrywos0810.azurecr.io/insurance:1.0"
          imagePullPolicy: Always
          name: insurance
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
  namespace: insurance
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
    - protocol: TCP
      name: insurance-http
      port: 80
      targetPort: 8081
  type: LoadBalancer
