#web-dev user (View access for API resources, Edit access for Web resources).
#api-dev user (View access to Web resources, Edit access to API resources)
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit
subjects:
- kind: Group
  namespace: web-dev
  name: ae7aba45-5ae5-4867-a3cf-35e9e4cda6f9
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- kind: Group
  namespace: web-dev
  name: ae7aba45-5ae5-4867-a3cf-35e9e4cda6f9
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: api-dev-access
    namespace: api-dev
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: edit
subjects:
- kind: Group
    namespace: api-dev
    name: 30eb4b25-085d-4aed-a85b-36c824f6e555
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: api-dev-access
    namespace: web-dev
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: view
subjects:
- kind: Group
    namespace: api-dev
    name: 30eb4b25-085d-4aed-a85b-36c824f6e555